version: 2

sources:
<<<<<<< HEAD
  - name: bigquery # are you sure you want to name it this? usually we name things after the data source, like 'stripe', or 'saleforce'
    schema: dbt_sample_data
    database: shiny-server-yottalogica
    tables: 
      - name: flights
=======
  - name: bigquery
    description: this is a abc
    schema: flights_test
    description: schema abc
    database: shiny-server-yottalogica
    description: shiny abc
    tables:
      - name: airports
        description: airports abc
      - name: flights
      - name: rawflights





>>>>>>> 2720d5311e916ae518deebd38a10a3c767b7d7ea
