version: 2

sources:
  - name: bigquery
    description: this is a abc
    schema: toyota_pilot
    description: schema abc
    database: shiny-server-yottalogica
    description: shiny abc
    tables:
      - name: Invoice_tbl
        description: This table is all about invoicing
        columns:
          - name: company
            description: "Here the company is the company which carried out the purchase"
          - name: invoice_type_code
            description: "There are multiple types to each invoice"
      - name: customer_tbl
      - name: employees_tbl
      - name: date_tbl
      - name: vehicle




